[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "consumerbr-resolution-prediction"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "catboost==1.2.10",
    "duckdb",
    "huggingface-hub",
    "joblib",
    "numpy",
    "pandas",
    "pyarrow",
    "requests",
    "scikit-learn",
    "scipy",
    "torch",
    "transformers",
    "tqdm"
]

[tool.setuptools.packages.find]
where = ["src"]